### PR TITLE
Minor bug of latest PR

### PR DESCRIPTION
**Pull request by hwany-j**
There is a minor bug in the latest PR. Sorry for the inconvenience.

### CODE REVIEW

**Comment by hwany-j** [comment]
It might be solved at #30

**Comment by samsja** [comment]
I still have error with the MNIST dataset

```
/home/user/miniconda/lib/python3.8/site-packages/torchvision/datasets/mnist.py:54: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-38-2bbc4de5725a> in <module>
      1 train_loader_b = torch.utils.data.DataLoader(
      2     mnist,
----> 3     sampler=ImbalancedDatasetSampler(mnist),
      4     batch_size=args.batch_size,
      5 )

~/.local/lib/python3.8/site-packages/torchsampler/imbalanced.py in __init__(self, dataset, indices, num_samples, callback_get_label)
     36         weights = 1.0 / label_to_count[df["label"]]
     37 
---> 38         self.weights = torch.DoubleTensor(weights)
     39 
     40     def _get_labels(self, dataset):

ValueError: too many dimensions 'Series'
```

**Comment by allanbatista** [comment]
> I still have error with the MNIST dataset
> 
> ```
> /home/user/miniconda/lib/python3.8/site-packages/torchvision/datasets/mnist.py:54: UserWarning: train_labels has been renamed targets
>   warnings.warn("train_labels has been renamed targets")
> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-38-2bbc4de5725a> in <module>
>       1 train_loader_b = torch.utils.data.DataLoader(
>       2     mnist,
> ----> 3     sampler=ImbalancedDatasetSampler(mnist),
>       4     batch_size=args.batch_size,
>       5 )
> 
> ~/.local/lib/python3.8/site-packages/torchsampler/imbalanced.py in __init__(self, dataset, indices, num_samples, callback_get_label)
>      36         weights = 1.0 / label_to_count[df["label"]]
>      37 
> ---> 38         self.weights = torch.DoubleTensor(weights)
>      39 
>      40     def _get_labels(self, dataset):
> 
> ValueError: too many dimensions 'Series'
> ```

The problem is because label_to_count is not a numpy array, to fix this issues, just use .values.

```
weights = 1.0 / label_to_count.values[df["label"]]
```

**Comment by hwany-j** [comment]
> > I still have error with the MNIST dataset
> > ```
> > /home/user/miniconda/lib/python3.8/site-packages/torchvision/datasets/mnist.py:54: UserWarning: train_labels has been renamed targets
> >   warnings.warn("train_labels has been renamed targets")
> > 
> > ---------------------------------------------------------------------------
> > ValueError                                Traceback (most recent call last)
> > <ipython-input-38-2bbc4de5725a> in <module>
> >       1 train_loader_b = torch.utils.data.DataLoader(
> >       2     mnist,
> > ----> 3     sampler=ImbalancedDatasetSampler(mnist),
> >       4     batch_size=args.batch_size,
> >       5 )
> > 
> > ~/.local/lib/python3.8/site-packages/torchsampler/imbalanced.py in __init__(self, dataset, indices, num_samples, callback_get_label)
> >      36         weights = 1.0 / label_to_count[df["label"]]
> >      37 
> > ---> 38         self.weights = torch.DoubleTensor(weights)
> >      39 
> >      40     def _get_labels(self, dataset):
> > 
> > ValueError: too many dimensions 'Series'
> > ```
> 
> The problem is because label_to_count is not a numpy array, to fix this issues, just use .values.
> 
> ```
> weights = 1.0 / label_to_count.values[df["label"]]
> ```

In my opinion, the error indicates line number 38, which means there is an error when converting weights to torch tensor. I
Hence, we have to change the type of `weights` from `pandas.Series` to `list`, or `numpy.array`. 
I added commits for this part.

**Pull request merged**
